config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :csv_exports, only: [:index, :create, :show, :destroy] do
    member do
      get 'download'
    end
  end

  resources :terms

  resources :controlled_vocabularies do
    member do
      get 'terms', action: 'terms', as: 'terms' # terms_controlled_vocabulary_path
      get 'export', action: 'export', as: 'export'
      get 'term_additional_fields', action: 'term_additional_fields', as: 'term_additional_fields' # term_additional_fields_controlled_vocabulary_path
    end
    collection do
      match 'search', via: [:get, :post]
    end
  end

  resources :digital_object_types

  resources :dynamic_fields
  resources :dynamic_field_groups do
    member do
      patch 'shift_child_field_or_group'
    end
  end
  resources :dynamic_field_group_categories

  resources :thumbs, only: [:show]

  resources :pid_generators
  resources :xml_datastreams

  resources :import_jobs, only: [:index, :new, :create, :show, :destroy] do
    member do
      get 'download_original_csv'
      get 'download_csv_without_successful_rows'
    end
    resources :digital_object_imports, only: [:index, :show]
  end

  resources :digital_object_imports, only: [:index, :show]

  resources :digital_objects do
    collection do
      match 'search', via: [:get, :post]
      match 'search_results_to_csv', via: [:get, :post]
      match 'data_for_editor', via: [:get, :post]
      post 'upload_assets'
      get 'upload_directory_listing'
      get 'titles_for_pids'
    end
    member do
      get 'data_for_ordered_child_editor'
      get 'download'
      get 'download_access_copy'
      get 'download_poster'
      get 'download_service_copy'
      get 'transcript', action: 'download_transcript'
      put 'transcript', action: 'update_transcript'
      get 'captions', action: 'download_captions'
      put 'captions', action: 'update_captions'
      get 'index_document', action: 'download_index_document'
      put 'index_document', action: 'update_index_document'
      get 'synchronized_transcript', action: 'download_synchronized_transcript'
      put 'synchronized_transcript', action: 'update_synchronized_transcript'
      delete 'clear_synchronized_transcript_and_reimport_transcript', action: 'clear_synchronized_transcript_and_reimport_transcript'
      get 'media_view'
      get 'mods'
      get 'xacml'
      put 'undelete', action: 'undestroy'
      put 'add_parent', action: 'add_parent'
      put 'remove_parents', action: 'remove_parents'
      post 'rotate_image', action: 'rotate_image'
      post 'regenerate_access_copy', action: 'regenerate_access_copy'
      get 'featured_region', action: 'query_featured_region'
      post 'featured_region', action: 'update_featured_region'
      post 'swap_order_of_first_two_child_assets', action: 'swap_order_of_first_two_child_assets'
    end
  end

  get '/login_check', to: 'pages#login_check'
  get '/get_csrf_token', to: 'pages#csrf_token'
  get '/home', to: 'pages#home', as: :home
  get '/system_information', to: 'pages#system_information', as: :system_information

  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    delete '/users/sign_out', to: 'users/sessions#destroy'
  end
  resources :users do
    collection do
      get 'current_user_data'
      get 'email_list'
    end
  end

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:admin?) && current_user.admin?
  end
  constraints resque_web_constraint do
    mount Resque::Server.new, at: "/resque"
  end

  resources :projects do
    resources :fieldsets, controller: 'projects/fieldsets', as: :project_fieldsets

    member do
      resource :permissions, controller: 'projects/permissions', only: [:edit, :update], as: :project_permissions
      resource :publish_targets, controller: 'projects/publish_targets', only: [:edit, :update], as: :project_publish_targets
      resource :dynamic_fields, controller: 'projects/dynamic_fields', only: [:edit, :update], as: :enabled_dynamic_fields
      get 'select_dynamic_fields_for_csv_export', action: 'select_dynamic_fields_for_csv_export', as: 'select_dynamic_fields_for_csv_export' # select_dynamic_fields_for_csv_export
      get 'select_dynamic_fields_csv_header_for_import', action: 'select_dynamic_fields_csv_header_for_import', as: 'select_dynamic_fields_csv_header_for_import' # select_dynamic_fields_csv_header_for_import
      get 'generate_csv_header_template', action: 'generate_csv_header_template', as: 'generate_csv_header_template'
    end

    collection do
      get 'where_current_user_can_create', action: 'where_current_user_can_create'
    end
  end

  resources :assignments do
    post 'commit', action: 'commit'
    member do
      put 'commit'
      get 'reject'
      put 'review'

      scope module: "assignments" do
        resource 'changeset', only: [:update, :edit, :show] do
          get 'proposed'
        end
      end
    end
  end

  resources :archived_assignments, only: [:index, :show, :destroy]

  root 'pages#home'

  get '/ui/v2', to: 'ui#v2'
  get '/ui/v2/*path', to: 'ui#v2'

  namespace :api, defaults: { format: :json } do
    namespace :v2 do
      resources :users, only: [:index, :create], param: :uid do
        collection do
          get '_self'
        end
        member do
          get '/', action: :show
          patch '/', action: :update
          post 'generate_new_api_key'
          get 'project_permissions', action: :project_permissions
          put 'project_permissions', action: :update_project_permissions
        end
      end

      resources :projects, only: [:index]
    end
  end

end

app/models/dynamic_field_group_category.rb
class DynamicFieldGroupCategory < ApplicationRecord
  has_many :dynamic_field_groups

  before_save :set_sort_order_if_blank

  def as_json(_options = {})
    {
      type: self.class.name,
      display_label: display_label,
      sort_order: sort_order,
      dynamic_field_groups: dynamic_field_groups
    }
  end

  private

    def set_sort_order_if_blank
      return unless sort_order.blank?

      temp = DynamicFieldGroupCategory.order(sort_order: :desc).pluck(:sort_order)
      new_sort_order = temp.blank? ? 0 : temp.first + 1
      self.sort_order = new_sort_order
    end
end

app/controllers/dynamic_field_group_categories_controller.rb
class DynamicFieldGroupCategoriesController < ApplicationController
  before_action :set_dynamic_field_group_category, only: [:show, :edit, :update, :destroy]

  # GET /dynamic_field_group_categories
  # GET /dynamic_field_group_categories.json
  def index
    @dynamic_field_group_categories = DynamicFieldGroupCategory.all
  end

  # GET /dynamic_field_group_categories/1
  # GET /dynamic_field_group_categories/1.json
  def show
  end

  # GET /dynamic_field_group_categories/new
  def new
    @dynamic_field_group_category = DynamicFieldGroupCategory.new
  end

  # GET /dynamic_field_group_categories/1/edit
  def edit
  end

  # POST /dynamic_field_group_categories
  # POST /dynamic_field_group_categories.json
  def create
    @dynamic_field_group_category = DynamicFieldGroupCategory.new(dynamic_field_group_category_params)

    respond_to do |format|
      if @dynamic_field_group_category.save
        format.html { redirect_to @dynamic_field_group_category, notice: 'Dynamic field category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dynamic_field_group_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @dynamic_field_group_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dynamic_field_group_categories/1
  # PATCH/PUT /dynamic_field_group_categories/1.json
  def update
    respond_to do |format|
      if @dynamic_field_group_category.update(dynamic_field_group_category_params)
        format.html { redirect_to @dynamic_field_group_category, notice: 'Dynamic field category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dynamic_field_group_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dynamic_field_group_categories/1
  # DELETE /dynamic_field_group_categories/1.json
  def destroy
    @dynamic_field_group_category.destroy
    respond_to do |format|
      format.html { redirect_to dynamic_field_group_categories_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_dynamic_field_group_category
      @dynamic_field_group_category = DynamicFieldGroupCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dynamic_field_group_category_params
      params.require(:dynamic_field_group_category).permit(:display_label, :sort_order)
    end
end

app/helpers/dynamic_field_group_categories_helper.rb
module DynamicFieldGroupCategoriesHelper
end

app/views/dynamic_field_group_categories/_form.html.erb
<%= form_for(@dynamic_field_group_category) do |f| %>
  <% if @dynamic_field_group_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dynamic_field_group_category.errors.count, "error") %> prohibited this dynamic_field_group_category from being saved:</h2>

      <ul>
      <% @dynamic_field_group_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :display_label %><br>
    <%= f.text_field :display_label %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br>
    <%= f.text_field :sort_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dynamic_field_group_categories/edit.html.erb
<h1>Editing dynamic_field_group_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @dynamic_field_group_category %> |
<%= link_to 'Back', dynamic_field_group_categories_path %>

app/views/dynamic_field_group_categories/index.html.erb
<h1>Listing dynamic_field_group_categories</h1>

<table>
  <thead>
    <tr>
      <th>Display label</th>
      <th>Sort order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dynamic_field_group_categories.each do |dynamic_field_group_category| %>
      <tr>
        <td><%= dynamic_field_group_category.display_label %></td>
        <td><%= dynamic_field_group_category.sort_order %></td>
        <td><%= link_to 'Show', dynamic_field_group_category %></td>
        <td><%= link_to 'Edit', edit_dynamic_field_group_category_path(dynamic_field_group_category) %></td>
        <td><%= link_to 'Destroy', dynamic_field_group_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dynamic field category', new_dynamic_field_group_category_path %>

app/views/dynamic_field_group_categories/new.html.erb
<h1>New dynamic_field_group_category</h1>

<%= render 'form' %>

<%= link_to 'Back', dynamic_field_group_categories_path %>

app/views/dynamic_field_group_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Display label:</strong>
  <%= @dynamic_field_group_category.display_label %>
</p>

<p>
  <strong>Sort order:</strong>
  <%= @dynamic_field_group_category.sort_order %>
</p>

<%= link_to 'Edit', edit_dynamic_field_group_category_path(@dynamic_field_group_category) %> |
<%= link_to 'Back', dynamic_field_group_categories_path %>