config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :csv_exports, only: [:index, :create, :show, :destroy] do
    member do
      get 'download'
    end
  end

  resources :terms

  resources :controlled_vocabularies do
    member do
      get 'terms', action: 'terms', as: 'terms' # terms_controlled_vocabulary_path
      get 'export', action: 'export', as: 'export'
      get 'term_additional_fields', action: 'term_additional_fields', as: 'term_additional_fields' # term_additional_fields_controlled_vocabulary_path
    end
    collection do
      match 'search', via: [:get, :post]
    end
  end

  resources :digital_object_types

  resources :dynamic_fields
  resources :dynamic_field_groups do
    member do
      patch 'shift_child_field_or_group'
    end
  end
  resources :dynamic_field_group_categories

  resources :thumbs, only: [:show]

  resources :pid_generators
  resources :xml_datastreams

  resources :import_jobs, only: [:index, :new, :create, :show, :destroy] do
    member do
      get 'download_original_csv'
      get 'download_csv_without_successful_rows'
    end
    resources :digital_object_imports, only: [:index, :show]
  end

  resources :digital_object_imports, only: [:index, :show]

  resources :digital_objects do
    collection do
      match 'search', via: [:get, :post]
      match 'search_results_to_csv', via: [:get, :post]
      match 'data_for_editor', via: [:get, :post]
      post 'upload_assets'
      get 'upload_directory_listing'
      get 'titles_for_pids'
    end
    member do
      get 'data_for_ordered_child_editor'
      get 'download'
      get 'download_access_copy'
      get 'download_poster'
      get 'download_service_copy'
      get 'transcript', action: 'download_transcript'
      put 'transcript', action: 'update_transcript'
      get 'captions', action: 'download_captions'
      put 'captions', action: 'update_captions'
      get 'index_document', action: 'download_index_document'
      put 'index_document', action: 'update_index_document'
      get 'synchronized_transcript', action: 'download_synchronized_transcript'
      put 'synchronized_transcript', action: 'update_synchronized_transcript'
      delete 'clear_synchronized_transcript_and_reimport_transcript', action: 'clear_synchronized_transcript_and_reimport_transcript'
      get 'media_view'
      get 'mods'
      get 'xacml'
      put 'undelete', action: 'undestroy'
      put 'add_parent', action: 'add_parent'
      put 'remove_parents', action: 'remove_parents'
      post 'rotate_image', action: 'rotate_image'
      post 'regenerate_access_copy', action: 'regenerate_access_copy'
      get 'featured_region', action: 'query_featured_region'
      post 'featured_region', action: 'update_featured_region'
      post 'swap_order_of_first_two_child_assets', action: 'swap_order_of_first_two_child_assets'
    end
  end

  get '/login_check', to: 'pages#login_check'
  get '/get_csrf_token', to: 'pages#csrf_token'
  get '/home', to: 'pages#home', as: :home
  get '/system_information', to: 'pages#system_information', as: :system_information

  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    delete '/users/sign_out', to: 'users/sessions#destroy'
  end
  resources :users do
    collection do
      get 'current_user_data'
      get 'email_list'
    end
  end

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:admin?) && current_user.admin?
  end
  constraints resque_web_constraint do
    mount Resque::Server.new, at: "/resque"
  end

  resources :projects do
    resources :fieldsets, controller: 'projects/fieldsets', as: :project_fieldsets

    member do
      resource :permissions, controller: 'projects/permissions', only: [:edit, :update], as: :project_permissions
      resource :publish_targets, controller: 'projects/publish_targets', only: [:edit, :update], as: :project_publish_targets
      resource :dynamic_fields, controller: 'projects/dynamic_fields', only: [:edit, :update], as: :enabled_dynamic_fields
      get 'select_dynamic_fields_for_csv_export', action: 'select_dynamic_fields_for_csv_export', as: 'select_dynamic_fields_for_csv_export' # select_dynamic_fields_for_csv_export
      get 'select_dynamic_fields_csv_header_for_import', action: 'select_dynamic_fields_csv_header_for_import', as: 'select_dynamic_fields_csv_header_for_import' # select_dynamic_fields_csv_header_for_import
      get 'generate_csv_header_template', action: 'generate_csv_header_template', as: 'generate_csv_header_template'
    end

    collection do
      get 'where_current_user_can_create', action: 'where_current_user_can_create'
    end
  end

  resources :assignments do
    post 'commit', action: 'commit'
    member do
      put 'commit'
      get 'reject'
      put 'review'

      scope module: "assignments" do
        resource 'changeset', only: [:update, :edit, :show] do
          get 'proposed'
        end
      end
    end
  end

  resources :archived_assignments, only: [:index, :show, :destroy]

  root 'pages#home'

  get '/ui/v2', to: 'ui#v2'
  get '/ui/v2/*path', to: 'ui#v2'

  namespace :api, defaults: { format: :json } do
    namespace :v2 do
      resources :users, only: [:index, :create], param: :uid do
        collection do
          get '_self'
        end
        member do
          get '/', action: :show
          patch '/', action: :update
          post 'generate_new_api_key'
          get 'project_permissions', action: :project_permissions
          put 'project_permissions', action: :update_project_permissions
        end
      end

      resources :projects, only: [:index]
    end
  end

end

app/controllers/api/v1/projects/field_sets_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Projects
      class FieldSetsController < ApplicationApiController
        before_action :ensure_json_request

        load_and_authorize_resource :project, find_by: :string_key, id_param: :project_string_key
        load_and_authorize_resource :field_set, through: :project
        skip_authorize_resource :field_set, only: :index

        # GET /projects/:string_key/field_sets
        def index
          render json: { field_sets: @project.field_sets }, status: :ok
        end

        # GET /projects/:string_key/field_sets/:id
        def show
          render json: { field_set: @field_set }, status: :ok
        end

        # POST /projects/:string_key/field_sets
        def create
          if @field_set.save
            render json: { field_set: @field_set }, status: :created
          else
            render json: errors(@field_set.errors.full_messages), status: :bad_request
          end
        end

        # PATCH /projects/:string_key/field_sets/:id
        def update
          if @field_set.update(field_set_params)
            render json: { fieldset: @field_set }, status: :ok
          else
            render json: errors(@field_set.errors.full_messages), status: :bad_request
          end
        end

        # DELETE /projects/:string_key/field_sets/:id
        def destroy
          if @field_set.destroy
            head :no_content
          else
            render json: errors('Deleting was unsuccessful.'), status: :bad_request
          end
        end

        private

          def field_set_params
            params.require(:field_set).permit(:display_label)
          end
      end
    end
  end
end

app/controllers/api/v1/projects_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ProjectsController < ApplicationApiController
      before_action :ensure_json_request

      load_and_authorize_resource find_by: :string_key, id_param: :string_key

      # GET /projects/:string_key
      def show
        if @project
          render json: { project: @project }, status: :ok
        else
          render json: errors('Not Found'), status: :not_found
        end
      end
    end
  end
end

app/controllers/api/v2/projects_controller.rb
class Api::V2::ProjectsController < Api::V2::BaseController
  # GET /api/v2/projects
  # Returns all projects (for admins) or projects user has any permission for
  def index
    if current_user.admin?
      projects = Project.all.order(:display_label)
    else
      # Users can see projects they have any permission for
      project_ids = current_user.project_permissions.pluck(:project_id)
      projects = Project.where(id: project_ids).order(:display_label)
    end

    render json: {
      projects: projects.map { |project| project_json(project) }
    }, status: :ok
  end

  private

    def project_json(project)
      {
        id: project.id,
        stringKey: project.string_key,
        displayLabel: project.display_label,
        pid: project.pid
      }
    end
end

app/controllers/projects/dynamic_fields_controller.rb
module Projects
  class DynamicFieldsController < SubresourceController
    include Hyacinth::ProjectsBehavior

    before_action :set_project
    before_action :require_appropriate_permissions!
    before_action :set_contextual_nav_options

    # GET /projects/1/dynamic_fields/edit?digital_object_type_id=1
    def edit
      @digital_object_type = DigitalObjectType.find(params[:digital_object_type_id])
    end

    # PATCH/PUT /projects/1/dynamic_fields?digital_object_type_id=1
    def update
      if @project.update(project_params)
        redirect_to edit_enabled_dynamic_fields_path(id: @project.id, digital_object_type_id: params[:digital_object_type_id]), notice: 'Your changes have been saved.'
      else
        render action: 'edit'
      end
    end

    def set_contextual_nav_options
      @contextual_nav_options['nav_title']['label'] = '&laquo; Back to Projects'.html_safe
      @contextual_nav_options['nav_title']['url'] = projects_path
    end

    private

      # Never trust parameters from the scary internet, only allow the white list through.
      def project_params
        params.require(:project).permit(
          :id, :display_label, :string_key, :pid_generator_id,
          enabled_dynamic_fields_attributes: [:id, :digital_object_type_id, :dynamic_field_id, :default_value, :required, :hidden, :locked, :_destroy, fieldset_ids: []],
          project_permissions_attributes: [:id, :_destroy, :user_id, :can_create, :can_read, :can_update, :can_delete, :can_publish, :is_project_admin],
          enabled_publish_targets_attributes: [:id, :_destroy, :publish_target_id],
          fieldset_attributes: [:display_label, :project_id]
        )
      end
  end
end

app/controllers/projects/permissions_controller.rb
module Projects
  class PermissionsController < SubresourceController
    include Hyacinth::ProjectsBehavior

    before_action :set_project
    before_action :require_appropriate_permissions!
    before_action :set_contextual_nav_options

    # GET /projects/1/permissions
    def show
    end

    # GET /projects/1/permissions/edit
    def edit
    end

    # PATCH/PUT /projects/1/permissions
    def update
      if @project.update(project_params)
        redirect_to edit_project_permissions_path(id: @project.id), notice: 'Your changes have been saved.'
      else
        render action: 'edit'
      end
    end

    private

      def set_contextual_nav_options
        @contextual_nav_options['nav_title']['label'] = '&laquo; Back to Projects'.html_safe
        @contextual_nav_options['nav_title']['url'] = projects_path
      end
  end
end

app/controllers/projects/publish_targets_controller.rb
module Projects
  class PublishTargetsController < SubresourceController
    include Hyacinth::ProjectsBehavior

    before_action :set_project, only: [:show, :edit, :update, :destroy]
    before_action :require_appropriate_permissions!
    before_action :set_contextual_nav_options

    # GET /projects/1/publish_targets/edit
    def edit
    end

    # PATCH/PUT /projects/1/publish_targets
    def update
      if @project.update(project_params)
        redirect_to edit_project_publish_targets_path(id: @project.id), notice: 'Your changes have been saved.'
      else
        render action: 'edit'
      end
    end

    private

      def set_contextual_nav_options
        @contextual_nav_options['nav_title']['label'] = '&laquo; Back to Projects'.html_safe
        @contextual_nav_options['nav_title']['url'] = projects_path
      end
  end
end

app/controllers/projects/subresource_controller.rb
module Projects
  class SubresourceController < ApplicationController
    def require_appropriate_permissions!
      require_project_permission!(@project, :project_admin)
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def do_recursive_enabled_dynamic_field_render(project_form_builder, digital_object_type, dynamic_field_or_dynamic_field_group)
    if dynamic_field_or_dynamic_field_group.is_a?(DynamicField)
      do_recursive_enabled_dynamic_field_render_field(project_form_builder, digital_object_type, dynamic_field_or_dynamic_field_group).html_safe
    else
      do_recursive_enabled_dynamic_field_render_group(project_form_builder, digital_object_type, dynamic_field_or_dynamic_field_group).html_safe
    end
  end

  def do_recursive_enabled_dynamic_field_render_field(project_form_builder, digital_object_type, dynamic_field_or_dynamic_field_group)
    project_object = project_form_builder.object
    html_to_return = '<div class="enabled_dynamic_field_row">'
    html_to_return += '<div class="row">'

    html_to_return += '<div class="col-md-2"><span class="label label-info" title="' + CGI.escapeHTML(dynamic_field_or_dynamic_field_group.string_key) + '">' + CGI.escapeHTML(dynamic_field_or_dynamic_field_group.display_label) + '</span></div>'

    enabled_dynamic_field = project_object.enabled_dynamic_fields.find { |o| o.dynamic_field == dynamic_field_or_dynamic_field_group && o.digital_object_type == digital_object_type } || project_object.enabled_dynamic_fields.build(dynamic_field: dynamic_field_or_dynamic_field_group, digital_object_type: digital_object_type)

    project_form_builder.fields_for(:enabled_dynamic_fields, enabled_dynamic_field) do |enabled_dynamic_field_form|
      dynamic_field = enabled_dynamic_field_form.object.dynamic_field

      html_to_return += enabled_dynamic_field_form.hidden_field(:id) if enabled_dynamic_field.id.present?
      html_to_return += enabled_dynamic_field_form.hidden_field(:dynamic_field_id) + enabled_dynamic_field_form.hidden_field(:digital_object_type_id)
      html_to_return += '<div class="col-md-1 check-stack">
        <div class="checkbox"><label>' + enabled_dynamic_field_form.check_box(:_destroy, { checked: enabled_dynamic_field.id.present? }, '0', '1') + ' Enabled</label></div>
        <div class="checkbox"><label>' + enabled_dynamic_field_form.check_box(:required) + ' Required</label></div>
        </div>'
      html_to_return += '<div class="col-md-1 check-stack">
        <div class="checkbox"><label>' + enabled_dynamic_field_form.check_box(:locked) + ' Locked</label></div>
        <div class="checkbox"><label>' + enabled_dynamic_field_form.check_box(:hidden) + ' Hidden</label></div>
      </div>'
      # TODO: Do we actually need the only_save_dynamic_field_group_if_present feature?
      # html_to_return += '<div class="col-md-2 check-stack">
      #  <div class="checkbox"><label>' + enabled_dynamic_field_form.check_box(:only_save_dynamic_field_group_if_present) + ' Only save field group if this field is present</label></div>
      # </div>'
      html_to_return += '<div class="col-md-4">' + enabled_dynamic_field_form.send((dynamic_field.dynamic_field_type == DynamicField::Type::TEXTAREA ? 'text_area' : 'text_field'), :default_value, class: 'form-control', placeholder: 'Default value (optional)') + '</div>'
      fieldsets = Fieldset.where(project: project_object)
      if fieldsets.present?
        html_to_return += '<div class="col-md-4">' + enabled_dynamic_field_form.collection_select(:fieldset_ids, fieldsets, :id, :display_label, {}, class: 'form-control multiselect', 'data-multiselect-nonselected-text'.to_sym => '- No fieldsets selected -', multiple: true) + '</div>'
      end
    end
    html_to_return += '<div class="clearfix"></div></div></div>'
    html_to_return
  end

  def do_recursive_enabled_dynamic_field_render_group(project_form_builder, digital_object_type, dynamic_field_or_dynamic_field_group)
    html_to_return = '<div class="enabled_dynamic_field_row">'
    html_to_return += '<h4 class="dynamic_field_group_label"><span class="label label-info">' + CGI.escapeHTML(dynamic_field_or_dynamic_field_group.display_label) + '</span></h4>'
    html_to_return += '<div class="indent">'

    dynamic_field_or_dynamic_field_group.child_dynamic_fields_and_dynamic_field_groups.each do |child_dynamic_field_or_dynamic_field_group|
      html_to_return += do_recursive_enabled_dynamic_field_render(project_form_builder, digital_object_type, child_dynamic_field_or_dynamic_field_group)
    end
    html_to_return += '</div>'
    html_to_return += '</div>'
    html_to_return
  end
end

app/views/projects/_edit_project_nav.html.erb
<h1 class="page-title">Project: <%= @project.display_label %></h1>

<!-- Nav tabs -->
<ul class="nav nav-tabs">
  <li <%= 'class="active"'.html_safe if params[:controller] == 'projects' && params[:action] == 'edit' %>>
      <%= link_to 'Core Data', edit_project_path(@project) %></li>
  <% DigitalObjectType.all.each do |digital_object_type| %>
  <li <%= 'class="active"'.html_safe if (params[:controller] == 'projects/dynamic_fields' && params[:action] == 'edit' && @digital_object_type == digital_object_type) %>>
      <%= link_to  digital_object_type.display_label + ' Fields', edit_enabled_dynamic_fields_path(@project, digital_object_type_id: digital_object_type.id) %>
  </li>
  <% end %>
  <li <%= 'class="active"'.html_safe if (params[:controller] == 'projects/permissions' && params[:action] == 'edit') %>>
      <%= link_to 'Permissions', edit_project_permissions_path(@project) %></li>
  <li <%= 'class="active"'.html_safe if (params[:controller] == 'projects/publish_targets' && params[:action] == 'edit') %>>
      <%= link_to 'Publish Targets', edit_project_publish_targets_path(@project) %></li>
  <li <%= 'class="active"'.html_safe if (params[:controller] == 'projects/fieldsets' && params[:action] == 'index') %>>
      <%= link_to 'Fieldsets', project_project_fieldsets_path(@project) %></li>
</ul>

app/views/projects/_form.html.erb
<%= render partial: 'edit_project_nav' unless params[:action] == 'new' || params[:action] == 'create' %>

<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <%= f.label :string_key %>
        <%= f.text_field :string_key, {class: 'form-control', disabled: ! @project.new_record?} %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="field">
        <%= f.label :display_label %>
        <%= f.text_field :display_label, {class: 'form-control'} %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <%= f.label :uri, 'Project URI' %>
        <%= f.text_field :uri, {class: 'form-control'} %>
      </div>
    </div>
      <div class="col-md-6">
      <div class="field">
        <%= f.label :short_label, 'Short Label' %>
        <%= f.text_field :short_label, {class: 'form-control'} %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <%= f.label :pid %>
        <%= f.text_field :pid, {class: 'form-control', disabled: true, value: @project.new_record? ? '- Automatically Generated -' : @project.pid} %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="field">
        <%= f.label :pid_generator_id, 'PID Generator' %>
        <% default_pid_generator = PidGenerator.find_by(namespace: HYACINTH[:default_pid_generator_namespace]) %>
        <%= f.collection_select(:pid_generator_id, PidGenerator.all.sort_by { |pid_generator| pid_generator.namespace }, :id, :namespace, { selected: default_pid_generator.present? ? default_pid_generator.id : nil }, {:class => 'form-control'}) %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="field">
        <%= f.label :default_storage_type, 'Default Storage Type' %>
        <%= f.select(:default_storage_type, Hyacinth::Storage::STORAGE_SCHEMES.sort, {}, {:class => 'form-control'}) %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="field">
        <%= f.label :default_access_storage_type, 'Default Access Storage Type' %>
        <%= f.select(:default_access_storage_type, Hyacinth::Storage::STORAGE_SCHEMES.sort, {}, {:class => 'form-control'}) %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit('Save', class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/projects/_import_export_csv_nav.html.erb
<h1 class="page-title">Project: <%= @project.display_label %></h1>

<!-- Nav tabs -->
<ul class="nav nav-tabs">
  <!-- fcd1, 09/28/15: Uncomment following when export functionality is implemented -->
  <!-- <li <%= 'class="active"'.html_safe if params[:action] == 'select_dynamic_fields_for_csv_export' %>><%= link_to 'Export Csv', select_dynamic_fields_for_csv_export_project_path(@project) %></li> -->
  <li <%= 'class="active"'.html_safe if params[:action] == 'upload_import_csv_file' %>><%= link_to 'Import Csv File', upload_import_csv_file_project_path(@project) %></li>
  <li <%= 'class="active"'.html_safe if params[:action] == 'select_dynamic_fields_csv_header_for_import' %>><%= link_to 'Generate Csv Headers', select_dynamic_fields_csv_header_for_import_project_path(@project) %></li>
</ul>

app/views/projects/edit_enabled_dynamic_fields.html.erb
<%= render partial: 'edit_project_nav' %>

<% dynamic_fields_that_are_enabled_for_this_digital_object_type = @project.enabled_dynamic_fields.where(digital_object_type: @digital_object_type).map{|enabled_dynamic_field| enabled_dynamic_field.dynamic_field} %>

<%= form_for(@project, :url => {:action => 'update_enabled_dynamic_fields'}) do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="nested_enabled_dynamic_fields_form">
    <% DynamicFieldGroupCategory.all.each do |dynamic_field_group_category| %>
      <%= "<h2>#{dynamic_field_group_category.display_label}</h2>".html_safe if dynamic_field_group_category.dynamic_field_groups.present? %>
      <% dynamic_field_group_category.dynamic_field_groups.each do |top_level_dynamic_field_group| %>
        <%= "<h3>#{top_level_dynamic_field_group.display_label}</h3>".html_safe if top_level_dynamic_field_group.get_child_dynamic_fields_and_dynamic_field_groups.present? %>
        <% top_level_dynamic_field_group.get_child_dynamic_fields_and_dynamic_field_groups.each do |dynamic_field_or_dynamic_field_group| %>
          <%= do_recursive_enabled_dynamic_field_render(f, @digital_object_type, dynamic_field_or_dynamic_field_group) %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit('Save', class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/projects/edit_project_permissions.html.erb
<%= render partial: 'edit_project_nav' %>

<% current_project_user_ids = @project.project_permissions.map{|project_permission| project_permission.user.id} %>
<% users_that_have_not_been_added_to_this_project = current_project_user_ids.blank? ? User.all : User.where('id NOT IN(' + current_project_user_ids.join(',') + ')') %>

<%= form_for(@project, :url => {:action => 'update_project_permissions'}) do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table id="project_permissions_user_add_form" class="table table-condensed table-bordered table-striped">
      <thead>
        <tr>
          <th class="col-md-5">Name</th>
          <th class="col-md-1">Read</th>
          <th class="col-md-1">Create</th>
          <th class="col-md-1">Update</th>
          <th class="col-md-1">Delete</th>
          <th class="col-md-2">Project Admin</th>
          <th class="col-md-1">Remove?</th>
        </tr>
      </thead>
      <tbody>
        <%= f.fields_for :project_permissions, @project.project_permissions.sort_by{ |project_permission| project_permission.user.full_name } do |project_permission_form| %>
          <tr>
            <td><%= project_permission_form.object.user.full_name %></td>
            <td><label><%= project_permission_form.check_box :can_read, :checked => 'checked', :disabled => 'disabled' %></label></td>
            <td><label><%= project_permission_form.check_box :can_create %></label></td>
            <td><label><%= project_permission_form.check_box :can_update %></label></td>
            <td><label><%= project_permission_form.check_box :can_delete %></label></td>
            <td><label><%= project_permission_form.check_box :is_project_admin %></label></td>
            <td><label><%= project_permission_form.check_box :_destroy %></label></td>
          </tr>
        <% end %>

        <% if users_that_have_not_been_added_to_this_project.length > 0 %>
          <%= f.fields_for :project_permissions, @project.project_permissions.build do |project_permission_form| %>
            <tr id="add-new-user-row">
              <td><%= project_permission_form.collection_select(:user_id, users_that_have_not_been_added_to_this_project, :id, :full_name, {:include_blank => '- Select a user -'}, {:class => 'form-control input-sm'}) %></td>
              <td><label><%= project_permission_form.check_box :can_read, :checked => 'checked', :disabled => 'disabled' %></label></td>
              <td><label><%= project_permission_form.check_box :can_create %></label></td>
              <td><label><%= project_permission_form.check_box :can_update %></label></td>
              <td><label><%= project_permission_form.check_box :can_delete %></label></td>
              <td><label><%= project_permission_form.check_box :is_project_admin %></label></td>
              <td></td>
            </tr>
          <% end %>
        <% else %>
          <tr><td colspan="7"><strong>All registered users have been added to this project.</strong></td></tr>
        <% end %>

      </tbody>
  </table>

  <div class="actions">
    <%= f.submit('Save', class: 'btn btn-primary') %>
  </div>

<% end %>

app/views/projects/fieldsets.html.erb
<%= render partial: 'edit_project_nav' %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Fieldset Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @fieldsets.each do |fieldset| %>
      <tr>
        <td class="col-xs-10"><%= fieldset.display_label %></td>
        <td class="col-xs-2 aligncenter"><%= link_to 'Edit', edit_fieldset_path(fieldset) %></td>
      </tr>
    <% end %>
    <%= '<tr><td colspan="2">No fieldsets have been created.</td></tr>'.html_safe if @fieldsets.length == 0 %>


  </tbody>
</table>

app/views/projects/index.html.erb
<h1>Projects</h1>

<div class="pagination-top"><%= paginate @projects, :window => 2 %></div>

<table class="table table-condensed table-bordered table-striped">
  <thead>
    <tr>
      <th>Display Label</th>
      <th>String Key</th>
      <th>PID</th>
      <th>PID Generator</th>
      <th>Download Header Template</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.display_label, edit_project_path(project) %></td>
        <td><%= project.string_key %></td>
        <td><%= project.pid %></td>
        <td><%= project.pid_generator.namespace %></td>
	<td><%= link_to "Download", generate_csv_header_template_project_path(project), {role: "button", class: "btn btn-default"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @projects, :window => 2 %>

app/views/projects/new.html.erb
<h1 class="page-title">New project</h1>

<%= render 'form' %>