config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :csv_exports, only: [:index, :create, :show, :destroy] do
    member do
      get 'download'
    end
  end

  resources :terms

  resources :controlled_vocabularies do
    member do
      get 'terms', action: 'terms', as: 'terms' # terms_controlled_vocabulary_path
      get 'export', action: 'export', as: 'export'
      get 'term_additional_fields', action: 'term_additional_fields', as: 'term_additional_fields' # term_additional_fields_controlled_vocabulary_path
    end
    collection do
      match 'search', via: [:get, :post]
    end
  end

  resources :digital_object_types

  resources :dynamic_fields
  resources :dynamic_field_groups do
    member do
      patch 'shift_child_field_or_group'
    end
  end
  resources :dynamic_field_group_categories

  resources :thumbs, only: [:show]

  resources :pid_generators
  resources :xml_datastreams

  resources :import_jobs, only: [:index, :new, :create, :show, :destroy] do
    member do
      get 'download_original_csv'
      get 'download_csv_without_successful_rows'
    end
    resources :digital_object_imports, only: [:index, :show]
  end

  resources :digital_object_imports, only: [:index, :show]

  resources :digital_objects do
    collection do
      match 'search', via: [:get, :post]
      match 'search_results_to_csv', via: [:get, :post]
      match 'data_for_editor', via: [:get, :post]
      post 'upload_assets'
      get 'upload_directory_listing'
      get 'titles_for_pids'
    end
    member do
      get 'data_for_ordered_child_editor'
      get 'download'
      get 'download_access_copy'
      get 'download_poster'
      get 'download_service_copy'
      get 'transcript', action: 'download_transcript'
      put 'transcript', action: 'update_transcript'
      get 'captions', action: 'download_captions'
      put 'captions', action: 'update_captions'
      get 'index_document', action: 'download_index_document'
      put 'index_document', action: 'update_index_document'
      get 'synchronized_transcript', action: 'download_synchronized_transcript'
      put 'synchronized_transcript', action: 'update_synchronized_transcript'
      delete 'clear_synchronized_transcript_and_reimport_transcript', action: 'clear_synchronized_transcript_and_reimport_transcript'
      get 'media_view'
      get 'mods'
      get 'xacml'
      put 'undelete', action: 'undestroy'
      put 'add_parent', action: 'add_parent'
      put 'remove_parents', action: 'remove_parents'
      post 'rotate_image', action: 'rotate_image'
      post 'regenerate_access_copy', action: 'regenerate_access_copy'
      get 'featured_region', action: 'query_featured_region'
      post 'featured_region', action: 'update_featured_region'
      post 'swap_order_of_first_two_child_assets', action: 'swap_order_of_first_two_child_assets'
    end
  end

  get '/login_check', to: 'pages#login_check'
  get '/get_csrf_token', to: 'pages#csrf_token'
  get '/home', to: 'pages#home', as: :home
  get '/system_information', to: 'pages#system_information', as: :system_information

  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    delete '/users/sign_out', to: 'users/sessions#destroy'
  end
  resources :users do
    collection do
      get 'current_user_data'
      get 'email_list'
    end
  end

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:admin?) && current_user.admin?
  end
  constraints resque_web_constraint do
    mount Resque::Server.new, at: "/resque"
  end

  resources :projects do
    resources :fieldsets, controller: 'projects/fieldsets', as: :project_fieldsets

    member do
      resource :permissions, controller: 'projects/permissions', only: [:edit, :update], as: :project_permissions
      resource :publish_targets, controller: 'projects/publish_targets', only: [:edit, :update], as: :project_publish_targets
      resource :dynamic_fields, controller: 'projects/dynamic_fields', only: [:edit, :update], as: :enabled_dynamic_fields
      get 'select_dynamic_fields_for_csv_export', action: 'select_dynamic_fields_for_csv_export', as: 'select_dynamic_fields_for_csv_export' # select_dynamic_fields_for_csv_export
      get 'select_dynamic_fields_csv_header_for_import', action: 'select_dynamic_fields_csv_header_for_import', as: 'select_dynamic_fields_csv_header_for_import' # select_dynamic_fields_csv_header_for_import
      get 'generate_csv_header_template', action: 'generate_csv_header_template', as: 'generate_csv_header_template'
    end

    collection do
      get 'where_current_user_can_create', action: 'where_current_user_can_create'
    end
  end

  resources :assignments do
    post 'commit', action: 'commit'
    member do
      put 'commit'
      get 'reject'
      put 'review'

      scope module: "assignments" do
        resource 'changeset', only: [:update, :edit, :show] do
          get 'proposed'
        end
      end
    end
  end

  resources :archived_assignments, only: [:index, :show, :destroy]

  root 'pages#home'

  get '/ui/v2', to: 'ui#v2'
  get '/ui/v2/*path', to: 'ui#v2'

  namespace :api, defaults: { format: :json } do
    namespace :v2 do
      resources :users, only: [:index, :create], param: :uid do
        collection do
          get '_self'
        end
        member do
          get '/', action: :show
          patch '/', action: :update
          post 'generate_new_api_key'
          get 'project_permissions', action: :project_permissions
          put 'project_permissions', action: :update_project_permissions
        end
      end

      resources :projects, only: [:index]
    end
  end

end

app/models/digital_object_import.rb
class DigitalObjectImport < ApplicationRecord
  enum :status, { pending: 0, success: 1, failure: 2 }
  serialize :digital_object_errors, type: Array, coder: YAML
  serialize :prerequisite_csv_row_numbers, type: Array, coder: YAML
  belongs_to :import_job
end

app/controllers/digital_object_imports_controller.rb
class DigitalObjectImportsController < ApplicationController
  def index
    @import_job = ImportJob.find params[:import_job_id]

    @status_filter = params[:status].present? && DigitalObjectImport.statuses.include?(params[:status].to_sym) ? params[:status].to_sym : nil
    page = params[:page]
    per_page = 50

    if @status_filter.present?
      @digital_object_imports = @import_job.digital_object_imports.where(status: DigitalObjectImport.statuses[@status_filter]).page(page).per(per_page)
    else
      @digital_object_imports = @import_job.digital_object_imports.page(page).per(per_page)
    end
  end

  def show
    @import_job = ImportJob.find params[:import_job_id] if params.key? :import_job_id
    @digital_object_import = DigitalObjectImport.find(params[:id])
  end
end

app/views/digital_object_imports/index.html.erb
<% if @import_job %>
<h1>Digital Object Imports for <%= link_to @import_job.name, import_job_path(@import_job) %></h1>
<% else %>
<h1>Digital Object Imports for all import jobs</h1>
<% end %>

<p>
<%= link_to(
	  'All',
	  import_job_digital_object_imports_path(@import_job),
	  class: 'btn btn-default btn-sm' + (@status_filter.nil? ? ' active' : '')
) %>

<% DigitalObjectImport.statuses.each do |status_string_key, _status_numberic_value| %>
  <%= link_to(
		status_string_key.capitalize,
		import_job_digital_object_imports_path(@import_job, {status: status_string_key}),
		class: 'btn btn-default btn-sm' + (@status_filter == status_string_key.to_sym ? ' active' : '')
  ) %>
<% end %>
</p>

<%= paginate @digital_object_imports %>

<table class="table table-condensed table-bordered table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>CSV Row</th>
      <th>Status</th>
      <th>Created at</th>
      <th>Updated at</th>
      <% if not @import_job %>
      <th>Import job</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @digital_object_imports.each do |digital_object_import| %>
      <tr>
	<% if @import_job %>
        <td><%= link_to digital_object_import.id, import_job_digital_object_import_path(digital_object_import.import_job,digital_object_import) %></td>
	<% else %>
        <td><%= link_to digital_object_import.id, digital_object_import_path(digital_object_import) %></td>
	<% end %>
        <td><%= digital_object_import.csv_row_number %></td>
        <td><%= digital_object_import.status %></td>
        <td><%= digital_object_import.created_at.localtime %></td>
        <td><%= digital_object_import.updated_at.localtime %></td>
	<% if not @import_job %>
	<td><%= link_to digital_object_import.import_job.name , import_job_path(digital_object_import.import_job) %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @digital_object_imports %>

<% if @import_job %>
<div>
<%= link_to 'Return to import job', import_job_path(@import_job) %>
</div>
<% end %>

app/views/digital_object_imports/show.html.erb
<h1>Digital Object Import (id: <%= @digital_object_import.id %>)</h1>
<p>
  <strong>Created on: </strong>
  <%= @digital_object_import.created_at.localtime %>
</p>
<p>
  <strong>Updated on: </strong>
  <%= @digital_object_import.updated_at.localtime %>
</p>
<p>
  <strong>Import Job:</strong>
  <%= link_to @digital_object_import.import_job.name, import_job_path(@digital_object_import.import_job) %>
</p>
<p>
  <strong>CSV Row Number:</strong>
  <%= @digital_object_import.csv_row_number %>
</p>
<p>
  <strong>Prerequisite Row Numbers:</strong>
  <%= @digital_object_import.prerequisite_csv_row_numbers.present? ? @digital_object_import.prerequisite_csv_row_numbers.join(', ') : 'None' %>
</p>
<p>
  <strong>Status:</strong>
  <%= @digital_object_import.status %>
</p>
<p>
  <strong>Digital object data:</strong>
  <br>
  <%= @digital_object_import.digital_object_data %>
</p>
<p>
  <strong>Errors:</strong>
  <br>
  <% if @digital_object_import.digital_object_errors.present? %>
    <ul><li><%= @digital_object_import.digital_object_errors.join('</li><li>').html_safe %></li></ul>
  <% else %>
    None
  <% end %>
</p>
<% if @import_job %>
<%= link_to 'Return to listing', import_job_digital_object_imports_path(@import_job) %>
<% else %>
<%= link_to 'Return to listing', digital_object_imports_path %>
<% end %>