config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :csv_exports, only: [:index, :create, :show, :destroy] do
    member do
      get 'download'
    end
  end

  resources :terms

  resources :controlled_vocabularies do
    member do
      get 'terms', action: 'terms', as: 'terms' # terms_controlled_vocabulary_path
      get 'export', action: 'export', as: 'export'
      get 'term_additional_fields', action: 'term_additional_fields', as: 'term_additional_fields' # term_additional_fields_controlled_vocabulary_path
    end
    collection do
      match 'search', via: [:get, :post]
    end
  end

  resources :digital_object_types

  resources :dynamic_fields
  resources :dynamic_field_groups do
    member do
      patch 'shift_child_field_or_group'
    end
  end
  resources :dynamic_field_group_categories

  resources :thumbs, only: [:show]

  resources :pid_generators
  resources :xml_datastreams

  resources :import_jobs, only: [:index, :new, :create, :show, :destroy] do
    member do
      get 'download_original_csv'
      get 'download_csv_without_successful_rows'
    end
    resources :digital_object_imports, only: [:index, :show]
  end

  resources :digital_object_imports, only: [:index, :show]

  resources :digital_objects do
    collection do
      match 'search', via: [:get, :post]
      match 'search_results_to_csv', via: [:get, :post]
      match 'data_for_editor', via: [:get, :post]
      post 'upload_assets'
      get 'upload_directory_listing'
      get 'titles_for_pids'
    end
    member do
      get 'data_for_ordered_child_editor'
      get 'download'
      get 'download_access_copy'
      get 'download_poster'
      get 'download_service_copy'
      get 'transcript', action: 'download_transcript'
      put 'transcript', action: 'update_transcript'
      get 'captions', action: 'download_captions'
      put 'captions', action: 'update_captions'
      get 'index_document', action: 'download_index_document'
      put 'index_document', action: 'update_index_document'
      get 'synchronized_transcript', action: 'download_synchronized_transcript'
      put 'synchronized_transcript', action: 'update_synchronized_transcript'
      delete 'clear_synchronized_transcript_and_reimport_transcript', action: 'clear_synchronized_transcript_and_reimport_transcript'
      get 'media_view'
      get 'mods'
      get 'xacml'
      put 'undelete', action: 'undestroy'
      put 'add_parent', action: 'add_parent'
      put 'remove_parents', action: 'remove_parents'
      post 'rotate_image', action: 'rotate_image'
      post 'regenerate_access_copy', action: 'regenerate_access_copy'
      get 'featured_region', action: 'query_featured_region'
      post 'featured_region', action: 'update_featured_region'
      post 'swap_order_of_first_two_child_assets', action: 'swap_order_of_first_two_child_assets'
    end
  end

  get '/login_check', to: 'pages#login_check'
  get '/get_csrf_token', to: 'pages#csrf_token'
  get '/home', to: 'pages#home', as: :home
  get '/system_information', to: 'pages#system_information', as: :system_information

  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    delete '/users/sign_out', to: 'users/sessions#destroy'
  end
  resources :users do
    collection do
      get 'current_user_data'
      get 'email_list'
    end
  end

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:admin?) && current_user.admin?
  end
  constraints resque_web_constraint do
    mount Resque::Server.new, at: "/resque"
  end

  resources :projects do
    resources :fieldsets, controller: 'projects/fieldsets', as: :project_fieldsets

    member do
      resource :permissions, controller: 'projects/permissions', only: [:edit, :update], as: :project_permissions
      resource :publish_targets, controller: 'projects/publish_targets', only: [:edit, :update], as: :project_publish_targets
      resource :dynamic_fields, controller: 'projects/dynamic_fields', only: [:edit, :update], as: :enabled_dynamic_fields
      get 'select_dynamic_fields_for_csv_export', action: 'select_dynamic_fields_for_csv_export', as: 'select_dynamic_fields_for_csv_export' # select_dynamic_fields_for_csv_export
      get 'select_dynamic_fields_csv_header_for_import', action: 'select_dynamic_fields_csv_header_for_import', as: 'select_dynamic_fields_csv_header_for_import' # select_dynamic_fields_csv_header_for_import
      get 'generate_csv_header_template', action: 'generate_csv_header_template', as: 'generate_csv_header_template'
    end

    collection do
      get 'where_current_user_can_create', action: 'where_current_user_can_create'
    end
  end

  resources :assignments do
    post 'commit', action: 'commit'
    member do
      put 'commit'
      get 'reject'
      put 'review'

      scope module: "assignments" do
        resource 'changeset', only: [:update, :edit, :show] do
          get 'proposed'
        end
      end
    end
  end

  resources :archived_assignments, only: [:index, :show, :destroy]

  root 'pages#home'

  get '/ui/v2', to: 'ui#v2'
  get '/ui/v2/*path', to: 'ui#v2'

  namespace :api, defaults: { format: :json } do
    namespace :v2 do
      resources :users, only: [:index, :create], param: :uid do
        collection do
          get '_self'
        end
        member do
          get '/', action: :show
          patch '/', action: :update
          post 'generate_new_api_key'
          get 'project_permissions', action: :project_permissions
          put 'project_permissions', action: :update_project_permissions
        end
      end

      resources :projects, only: [:index]
    end
  end

end

app/models/controlled_vocabulary.rb
class ControlledVocabulary < ApplicationRecord
  before_create :create_corresponding_uri_service_vocabulary, unless: :corresponding_uri_service_vocabulary_exists?
  after_destroy :delete_corresponding_uri_service_vocabulary, unless: :corresponding_uri_service_vocabulary_has_terms?

  before_update :update_uri_service_display_label

  attr_accessor :display_label

  def display_label
    @display_label ||= begin
      new_record? ? '' : UriService.client.find_vocabulary(string_key)[:display_label]
    end
  end

  def update_uri_service_display_label
    UriService.client.update_vocabulary(string_key, @display_label)
  end

  def corresponding_uri_service_vocabulary_exists?
    UriService.client.find_vocabulary(string_key).present?
  end

  def create_corresponding_uri_service_vocabulary
    UriService.client.create_vocabulary(string_key, display_label) unless corresponding_uri_service_vocabulary_exists?
  end

  def corresponding_uri_service_vocabulary_has_terms?
    UriService.client.list_terms(string_key).length > 0
  end

  def delete_corresponding_uri_service_vocabulary
    UriService.client.delete_vocabulary(string_key) unless corresponding_uri_service_vocabulary_has_terms?
  end
end

app/controllers/controlled_vocabularies_controller.rb
class ControlledVocabulariesController < ApplicationController
  include ActionController::Live

  before_action :set_controlled_vocabulary, only: [:show, :edit, :update, :destroy, :terms, :export, :term_additional_fields]
  before_action :require_appropriate_permissions!
  before_action :set_contextual_nav_options

  # GET /controlled_vocabularies
  # GET /controlled_vocabularies.json
  def index
    # Get all registered ControlledVocabularies
    @controlled_vocabularies = ControlledVocabulary.all.order(:string_key)

    # Also get additional controlled vocabularies from UriService that haven't been registered
    controlled_vocabulary_string_keys = @controlled_vocabularies.map(&:string_key)
    @additional_uri_service_controlled_vocabularies = UriService.client.list_vocabularies(1000) # Ridiculously high limit to show all
    @additional_uri_service_controlled_vocabularies.delete_if { |uri_service_vocabulary| controlled_vocabulary_string_keys.include?(uri_service_vocabulary['string_key']) }
  end

  # GET /controlled_vocabularies/1
  # GET /controlled_vocabularies/1.json
  def show
  end

  # GET /controlled_vocabularies/new
  def new
    @controlled_vocabulary = ControlledVocabulary.new
    @controlled_vocabulary.string_key = params[:string_key] if params[:string_key].present?
    @controlled_vocabulary.display_label = params[:display_label] if params[:display_label].present?
  end

  # GET /controlled_vocabularies/1/edit
  def edit
  end

  # POST /controlled_vocabularies
  # POST /controlled_vocabularies.json
  def create
    @controlled_vocabulary = ControlledVocabulary.new(controlled_vocabulary_params)

    respond_to do |format|
      if @controlled_vocabulary.save
        format.html { redirect_to edit_controlled_vocabulary_path(@controlled_vocabulary), notice: 'Controlled vocabulary was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /controlled_vocabularies/1
  # PATCH/PUT /controlled_vocabularies/1.json
  def update
    respond_to do |format|
      if @controlled_vocabulary.update(controlled_vocabulary_params)
        format.html { redirect_to edit_controlled_vocabulary_path(@controlled_vocabulary), notice: 'Controlled vocabulary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @controlled_vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /controlled_vocabularies/1
  # DELETE /controlled_vocabularies/1.json
  def destroy
    @controlled_vocabulary.destroy
    respond_to do |format|
      format.html { redirect_to controlled_vocabularies_url }
      format.json { head :no_content }
    end
  end

  def terms
    @page = params.fetch(:page, 1).to_i

    if request.format == 'text/html'
      @per_page = params.fetch(:per_page, 20).to_i
    else
      @per_page = params.fetch(:per_page, 5).to_i
    end
    @per_page = 5 if @per_page < 5 # Show at least 5 terms per page

    if params[:q].blank?
      @terms = UriService.client.list_terms(@controlled_vocabulary.string_key, @per_page + 1, ((@page - 1) * @per_page))
    else
      @terms = UriService.client.find_terms_by_query(@controlled_vocabulary.string_key, params[:q], @per_page + 1, ((@page - 1) * @per_page))
    end

    respond_to do |format|
      # Render normal html view
      format.html

      format.json do
        render json: {
          terms: @terms[0..(@per_page - 1)],
          more_available: (@terms.length > @per_page),
          current_user_can_add_terms: current_user.can_manage_controlled_vocabulary_terms?(@controlled_vocabulary)
        }
      end
    end
  end

  # An endpoint for exporting an entire controlled vocabulary
  def export
    respond_to do |format|
      # This endpoint only responds to CSV
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = "attachment; filename=#{@controlled_vocabulary.string_key}.csv"

        vocabulary_additional_field_keys = TERM_ADDITIONAL_FIELDS.fetch(@controlled_vocabulary.string_key, {}).keys

        page = 1
        per_page = 250
        begin
          response.stream.write CSV.generate_line(['value', 'authority', 'type', 'uri'] + vocabulary_additional_field_keys)
          loop do
            terms = UriService.client.list_terms(@controlled_vocabulary.string_key, per_page, (page - 1) * per_page)
            break if terms.blank?

            terms.each do |term|
              response.stream.write CSV.generate_line(
                (['value', 'authority', 'type', 'uri'] + vocabulary_additional_field_keys).map { |field_key| term[field_key] }
              )
            end

            page += 1
            sleep 0.05 # sleep after each iteration so this endpoint doesn't overwhelm solr by making too many rapid queries
          end
        ensure
          response.stream.close
        end
      end
    end
  end

  def term_additional_fields
    respond_to do |format|
      format.json { render json: TERM_ADDITIONAL_FIELDS.fetch(@controlled_vocabulary.string_key, {}) }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_controlled_vocabulary
      if params[:id] =~ /[0-9]+/
        @controlled_vocabulary = ControlledVocabulary.find(params[:id])
      else
        @controlled_vocabulary = ControlledVocabulary.find_by(string_key: params[:id])
      end

      raise ActionController::RoutingError, 'Controlled vocabulary not found' if @controlled_vocabulary.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def controlled_vocabulary_params
      params.require(:controlled_vocabulary).permit(:string_key, :display_label, :require_controlled_vocabulary_manager_permission)
    end

    def set_contextual_nav_options
      case params[:action]
      when 'index'
        @contextual_nav_options['nav_title']['label'] = 'Controlled Vocabularies'.html_safe
      when 'search'
        @contextual_nav_options['nav_title']['label'] = '&laquo; Back to Controlled Vocabularies'.html_safe
        @contextual_nav_options['nav_title']['url'] = controlled_vocabularies_path
      when 'new'
        @contextual_nav_options['nav_title']['label'] = '&laquo; Back to Controlled Vocabularies'.html_safe
        @contextual_nav_options['nav_title']['url'] = controlled_vocabularies_path
      when 'edit', 'update'
        @contextual_nav_options['nav_title']['label'] = '&laquo; Back to Controlled Vocabularies'.html_safe
        @contextual_nav_options['nav_title']['url'] = controlled_vocabularies_path

        @contextual_nav_options['nav_items'].push(label: 'Manage Terms', url: terms_controlled_vocabulary_path(@controlled_vocabulary))
      when 'terms'
        @contextual_nav_options['nav_title']['label'] =  '&laquo; Back to Controlled Vocabularies'.html_safe
        @contextual_nav_options['nav_title']['url'] = controlled_vocabularies_path
      end
      set_admin_contextual_nav_options
      set_manager_contextual_nav_options
    end

    def set_admin_contextual_nav_options
      return unless current_user.admin?
      case params[:action]
      when 'index'
        @contextual_nav_options['nav_items'].push(label: 'Add New Controlled Vocabulary', url: new_controlled_vocabulary_path)
      when 'edit', 'update'
        @contextual_nav_options['nav_items'].push(label: 'Delete This Controlled Vocabulary', url: controlled_vocabulary_path(@controlled_vocabulary), options: { method: :delete, data: { confirm: 'Are you sure you want to delete this Controlled Vocabulary?' } })
      end
    end

    def set_manager_contextual_nav_options
      return unless current_user.can_manage_controlled_vocabulary_terms?(@controlled_vocabulary)
      @contextual_nav_options['nav_items'].push(label: 'New Term', url: new_term_path(controlled_vocabulary_string_key: @controlled_vocabulary.string_key)) if params[:action] == 'terms'
    end

    def require_appropriate_permissions!
      case params[:action]
      when 'index', 'terms', 'term_additional_fields', 'export'
        # Do nothing
      else
        require_hyacinth_admin!
      end
    end
end

app/helpers/controlled_vocabularies_helper.rb
module ControlledVocabulariesHelper
end

app/views/controlled_vocabularies/_form.html.erb
<%= form_for(@controlled_vocabulary) do |f| %>
  <% if @controlled_vocabulary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@controlled_vocabulary.errors.count, "error") %> prohibited this controlled_vocabulary from being saved:</h2>

      <ul>
      <% @controlled_vocabulary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :string_key, 'String key (cannot be changed)' %><br>
    <%= f.text_field :string_key, {class: 'form-control', disabled: ( ! @controlled_vocabulary.new_record? )} %>
  </div>
  <div class="field">
    <%= f.label :display_label %><br>
    <%= f.text_field :display_label, {class: 'form-control'} %>
  </div>

  <div class="field">
    <%= f.label(:require_controlled_vocabulary_manager_permission, (f.check_box(:require_controlled_vocabulary_manager_permission)).html_safe + ' Require Controlled Vocabulary Manager Permission') %>
  </div>

  <div class="field">
    <%= f.label(:prohibit_temp_terms, (f.check_box(:prohibit_temp_terms)).html_safe + ' Prohibit Temp Term Creation') %>
  </div>

  <div class="actions">
    <%= f.submit('Save', class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/controlled_vocabularies/_terms_prev_next.html.erb
<div class="term-paging">
  <% if @page > 1 %>
    <%= link_to '&laquo; Previous'.html_safe, terms_controlled_vocabulary_path(@controlled_vocabulary, {page: @page-1, per_page: @per_page, q: params[:q]}), class: 'pull-left' %>
  <% end %>
  <% if @terms.length > @per_page %>
    <%= link_to 'Next &raquo;'.html_safe, terms_controlled_vocabulary_path(@controlled_vocabulary, {page: @page+1, per_page: @per_page, q: params[:q]}), class: 'pull-right' %>
  <% end %>
  <div class="clearfix"></div>
</div>

app/views/controlled_vocabularies/edit.html.erb
<h1>Controlled Vocabulary: <%= @controlled_vocabulary.display_label %></h1>

<%= render 'form' %>

app/views/controlled_vocabularies/index.html.erb
<h1>Controlled Vocabularies</h1>

<% if @controlled_vocabularies.blank? && @additional_uri_service_controlled_vocabularies.blank? %>
  No Controlled Vocabularies have been created yet.
<% else %>

  <% if @controlled_vocabularies.present? %>
    <h3>Registered Controlled Vocabularies</h3>
    <table class="table table-bordered table-striped">
      <tbody>
        <% @controlled_vocabularies.each do |controlled_vocabulary| %>
          <tr>
            <td class="col-xs-4"><%= controlled_vocabulary.display_label %></td>
            <td class="col-xs-2 aligncenter"><%= link_to 'Edit', edit_controlled_vocabulary_path(controlled_vocabulary) %></td>
            <td class="col-xs-3 aligncenter"><%= link_to 'Export Terms (CSV)', export_controlled_vocabulary_path(controlled_vocabulary, format: 'csv') %></td>
            <td class="col-xs-3 aligncenter"><%= link_to (current_user.can_manage_controlled_vocabulary_terms?(controlled_vocabulary) ? 'Manage' : 'View') + ' Terms', terms_controlled_vocabulary_path(controlled_vocabulary) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <% if @additional_uri_service_controlled_vocabularies.present? %>
  <h3>Unregistered Controlled Vocabularies</h3>
  <table class="table table-bordered table-striped">
    <tbody>
      <% @additional_uri_service_controlled_vocabularies.each do |uri_service_controlled_vocabulary| %>
        <tr>
          <td class="col-xs-7"><%= uri_service_controlled_vocabulary['display_label'] %></td>
          <td class="col-xs-2 aligncenter"><%= link_to 'Add', new_controlled_vocabulary_path(string_key: uri_service_controlled_vocabulary['string_key'], display_label: uri_service_controlled_vocabulary['display_label']) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>

<% end %>

app/views/controlled_vocabularies/new.html.erb
<h1>New Controlled Vocabulary</h1>

<%= render 'form' %>

app/views/controlled_vocabularies/terms.html.erb
<h1><%= @controlled_vocabulary.display_label %></h1>

<%= form_tag(terms_controlled_vocabulary_path(@controlled_vocabulary), {method: 'get'}) do |f| %>
  <div class="input-group">
      <%= text_field_tag :q, params[:q], class: 'form-control input-sm', placeholder: 'Search for values...' %>
      <div class="input-group-btn">
        <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, terms_controlled_vocabulary_path(@controlled_vocabulary), class: 'btn btn-default btn-sm' %>
        <%= submit_tag 'Search', class: 'btn btn-default btn-sm', name: nil %>
      </div>
  </div>
<% end %>
<br />

<% if @terms.length == 0 %>
    No Terms found.
<% else %>

  <%= render 'terms_prev_next' %>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th class="col-xs-4">Value</th>
        <th class="col-xs-2">Authority</th>
        <th class="col-xs-2">Type</th>
        <th class="col-xs-2">URI</th>
        <th class="col-xs-2"></th>
      </tr>
    </thead>
    <tbody>
      <% counter = 1 %>
      <% @terms.each_with_index do |term| %>
        <tr>
          <td><%= term['value'] %></td>
          <td><%= term['authority'] %></td>
          <td>
            <% if term['type'] == UriService::TermType::TEMPORARY %>
              <strong><%= term['type'] %></strong>
            <% else %>
              <%= term['type'] %>
            <% end %>
          </td>
          <td><%= term['uri'] %></td>
          <td class="aligncenter"><%= link_to 'View', term_path(term['internal_id']), class: 'btn btn-default btn-xs' %> <%= link_to 'Edit', edit_term_path(term['internal_id']), class: 'btn btn-default btn-xs' %></td>
        </tr>
        <%
          if counter == @per_page
            break
          else
            counter += 1
          end
        %>
      <% end %>
    </tbody>
  </table>

  <%= render 'terms_prev_next' %>

<% end %>